### ISSUE TITLE
ToDo for the KIT tutorial

### ISSUE THREAD

**Issue by willirath** [willirath/pangeo-tutorial#1]
We're limited to 1 hour and will run all this via a video-conference. So I'll prepare for 30-40 minutes of talking.

Route through the materials:

- `pangeo-tutorial/notebooks/google-cloud/gmet_ensemble.ipynb` to get into Xarray and Intake.

- `pangeo-tutorial/notebooks/google-cloud/ocean_ssh_example.ipynb` but focused on visualization with gvplot.

- Brief tour of the other materials focused on how to self study.

- If time: `pangeo-tutorial/notebooks/intake.ipynb`

ToDo:

- [ ] Add and auto-load `welcome_kit2020.ipynb`
- [ ] Update ssh and GMET examples to use `gvplot`
- [ ] Add CMIP6 example?

**Comment by willirath** [comment]
Pinging @jbusecke: I'm preparing a Pangeo tutorial for atmospheric scientists. Do you have a quick pointer to a notebook showing off how to use existing CMIP data in the cloud?

**Comment by jbusecke** [comment]
I got a few bits and pieces. Not really a 'one-stop-shop' notebook.

[Tutorial how to use `cmip6_preprocessing`](https://github.com/jbusecke/cmip6_preprocessing/blob/master/notebooks/tutorial.ipynb). This might not be the most exciting thing, but it is worth spreading the word. Using this little tool helps a lot with making comparison between models. I use it ALL THE TIME, and would certainly appreciate the promo 😁 . The example right at the end would work nicely.

[Some more tutorials](https://github.com/jbusecke/cmip6-hackathon-demos) These are quite old. Currently checking if they still run, but those are nice as an example what is possible. Not sure if using xgcm is on the agenda? Then this might be a great example.

[Comparing extent of Oxygen Minimum Zones at 250 m depth](https://github.com/mfreilich1/cmip6hack-ocean-bgc/blob/master/notebooks/final_analysis.ipynb) This is a huge notebook. My parts are under "Comparing the Oxygen Minumum Zones (OMZs) in in the global ocean between CMIP6 models".

I could spend a few minutes combining things, if you like any of this 😆 

Sorry for the disarray.

**Comment by jbusecke** [comment]
> Some more tutorials These are quite old. Currently checking if they still run,

Yeah they need some fixin.... Give me a few minutes to try to get them back up. 

Let me know if any of these looks particularly suited.

**Comment by jbusecke** [comment]
Yeah there were some breaking changes in `cmip6_preprocessing` before I officially released it, so the xgcm notebook needs some more serious work. When is the workshop? I am planning to work on the xgcm preprocessing soon.

**Comment by willirath** [comment]
Thanks @jbusecke! As I only have an hour in total, xgcm is out of scope for this.

I'll probably go for a simple demo of using intake with your preprocessing to unify naming conventions. This notebook looks like it'll get me started quickly: <https://github.com/jbusecke/cmip6_preprocessing/blob/3bc9a4c4789d5a6ebf97a4989b8538fbb04b9f0f/notebooks/tutorial.ipynb>.

**Comment by jbusecke** [comment]
Thats awesome, @willirath. Let me know if any questions arise.
